# Лабораторная работа 2. Элементы линейной алгебры. Шаргин Иван

In [10]:
import numpy as np
import matplotlib.pyplot as plt

Решим СЛАУ A * u = f 

## 1. Метод Гаусса

Функция Gauss_solve реализует метод Гаусса, принимает на вход матрицу A, вектор правой части f, возвращает решение u

In [11]:
def Gauss(A, f):
    """Функция Gauss реализует метод Гаусса, 
    принимает на вход матрицу A, вектор правой части f, 
    возвращает решение СЛАУ"""
    leading_element_inds = np.transpose(np.nonzero(np.abs(A) == np.abs(A).max()))[0]
    A_f = np.hstack((A, f))
    A_f[[0, leading_element_inds[0]]] = A_f[[leading_element_inds[0], 0]]
    A_f[:, [0, leading_element_inds[1]]] = A_f[:, [leading_element_inds[1], 0]]

    for j in range(0, A_f.shape[0] - 1):
        for i in range(j + 1, A_f.shape[0]):
            k = A_f[i, j] / A_f[j, j]
            A_f[i, j:] = A_f[i, j:] - A_f[j, j:] * k
    
            
    for j in range(A_f.shape[0] - 1, 0, -1):
        for i in range(j - 1, -1, -1):
            k = A_f[i, j] / A_f[j, j]
            A_f[i, :] = A_f[i, :] - A_f[j, :] * k
    
            
    for i in range(A_f.shape[0]):
        A_f[i, :] = A_f[i, :] / A_f[i, i]
    
 
    answer = A_f[:, -1]
    answer[[0, leading_element_inds[1]]] = answer[[leading_element_inds[1], 0]]
    
    
    return answer  


In [12]:
A_test = np.array([[5.0, 7.0, 6.0], [4.0, 8.0, 3.0],  [-1.0, 6.0, 2.0]])
print(A_test)
f_test = np.array([[35.0], [25.0], [10.0]])
print(f_test)
print(Gauss(A_test, f_test))

[[ 5.  7.  6.]
 [ 4.  8.  3.]
 [-1.  6.  2.]]
[[35.]
 [25.]
 [10.]]
[2. 1. 3.]


## 2.Метод Якоби решения СЛАУ

In [22]:
def Jacobi(A, f, e):
    """Функция реализует метод Якоби решения СЛАУ.
    Принимает матрицу А левой части и вектор f правой части, 
    необходимую точность e. Возвращает вектор решения"""
    N = A.shape[0]
    diagonal = A.diagonal()
    
    x = []
    x.append(f)
    x_new = f
    error = 100    
    
    while error >= e:
        a_x = A.dot(x[-1])
        x.append(np.array([(f[i] - a_x[i] + x[-1] [i] * diagonal[i]) / diagonal[i] for i in range(N)]))
        
        error = np.linalg.norm(x[-2] - x[-1]) 
                 
    return (x[-1])  

In [24]:
A_j = np.array([[5., 2.], [1., 5.]])
f_j = np.array([[7.], [6.]])

In [26]:
Jacobi(A_j, f_j, 0.01)


array([[0.998976 ],
       [0.9993856]])

In [ ]:
A_test.dot(f_test)